apiVersion: apps/v1
kind: Deployment
metadata:
 name: my-pw7-development
 labels:
  app: my-k8s-deployment
spec:
 replicas: 2
 selector:
  matchLabels:
   project: pw7
 template:
  metadata:
   labels:
    project: pw7
  spec:
   containers:
    - name: pw7-nginx
      image: nginx:latest
      ports:
       - containerPort: 80